Algoritmo "Uso do PARA com incremento aleatorio"

Var
i, aleatorioMaximo, aleatorioMinimo, pass : inteiro

Inicio

repita
      aleatorio 1,100
      leia (aleatorioMaximo)
      leia (aleatorioMinimo)
      aleatorio off
ate aleatorioMaximo >  aleatorioMinimo
limpatela

aleatorio 1,5
leia (pass)
aleatorio off
limpatela

para i de aleatorioMinimo ate aleatorioMaximo passo pass faca
     Escreval (i)
fimpara

Fimalgoritmo